liquibase:
  enabled: true
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.freesmtpservers.com
    port: 25
    test-connection: false
    username:
    password:
    properties:
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/evcdb
    username: root
    password: mysql
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
afya:
  yangu:
    platform:
      config-location: classpath:quartz.properties
logging:
  level:
    afya.yangu.platform: debug

# Running with Java 9
# > mvnw clean package -DskipTests
# > java --add-modules java.xml.bind --illegal-access=warn -jar target\quartz-manager.jar

